[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1050ee9c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/327a5d35-85da-469a-8677-bf01040fd594
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1050eead0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/327a5d35-85da-469a-8677-bf01040fd594
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1050eee00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/327a5d35-85da-469a-8677-bf01040fd594