[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1057f8490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/04182af3-6109-4bea-ac1e-c269d4832a50
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1057f85a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/04182af3-6109-4bea-ac1e-c269d4832a50
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1057f88d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/04182af3-6109-4bea-ac1e-c269d4832a50