[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1050ecaf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d33e321a-cafd-4918-9b79-29acc938b880
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1050ecd10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d33e321a-cafd-4918-9b79-29acc938b880
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1050ed040>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d33e321a-cafd-4918-9b79-29acc938b880