[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105077770>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4420094c-a40d-473b-9fcf-3a2020b5a3c1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104f3bdf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4420094c-a40d-473b-9fcf-3a2020b5a3c1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104f3bbd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4420094c-a40d-473b-9fcf-3a2020b5a3c1